language: ruby
before_install:
 - gem install bundler
 - bundle install
script: bundle exec rake
rvm:
  - 1.9.3
  - 2.2
  - jruby-19mode
  - rbx-2

gemfile:
  - gemfiles/active_model_4.1.gemfile
  - gemfiles/active_model_4.2.gemfile
